name: build

on: [push]
jobs:
  Build_Lotus:
    runs-on: ubuntu-latest
    container:
      image: centos:7
      options: --privileged # Needed for loading the fuse module.
    permissions:
      contents: read
    steps:
    - name: Prepare the system
      run: |
        yum install -y centos-release-scl epel-release
        yum update -y
        yum install -y wget patch python3 python3-pip fuse-libs file cmake3 devtoolset-11 rh-git227 # git>=2.18 for checkout@v3.
        pip3 install sphinx
        mkdir -p /usr/local/bin
        ln -s /usr/bin/cmake3 /usr/local/bin/cmake
        ln -s /usr/bin/ctest3 /usr/local/bin/ctest
    - name: Install ncurses
      shell: 'scl enable devtoolset-11 "bash {0}"'
      run: |
        wget -O /ncurses.tar.gz https://invisible-island.net/archives/ncurses/ncurses-6.3.tar.gz
        mkdir /ncurses
        tar xf /ncurses.tar.gz --strip-components=1 -C /ncurses
        mkdir /ncurses-prefix
        pushd /ncurses
        env TERMINFO= TERMINFO_DIRS= ./configure --without-shared
        make -j$(nproc)
        make install DESTDIR=/ncurses-prefix
        popd
    - name: Pull source code from remote
      shell: 'scl enable devtoolset-11 rh-git227 "bash {0}"'
      run: 'git clone https://github.com/fish-shell/fish-shell'
    - name: Inject building script
      shell: 'scl enable devtoolset-11 rh-git227 "bash {0}"'
      run: 'cd fish-shell && curl -sL "https://github.com/TeaHouseLab/Lotus/blob/main/tar_with_dependence.sh?raw=true" >build_tools/tar_with_dependence.sh'
    - name: Start building
      shell: 'scl enable devtoolset-11 rh-git227 "bash {0}"'
      env:
        FISH_NCURSES_ROOT: /ncurses-prefix/usr
        LC_CTYPE: en_US.UTF-8
      run: 'cd fish-shell && chmod +x ./build_tools/tar_with_dependence.sh && ./build_tools/tar_with_dependence.sh'
    - uses: actions/upload-artifact@v3
      run: 'pwd && ls'
      with:
        path: '*.tar.gz'
        retention-days: 1